services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      # - ./_docker-volumes/data:/data/db     # search in doc
      - mongo-db:/data/db     
    networks:
      - mern-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: messanger

    container_name: messanger
    working_dir: /app
    ports:
      - 5000:5000
      - 35729:35729

    restart: always
    volumes:
      - .:/app

    # env_file: 
      # - .env 

    environment:
      NODE_ENV: development
      DB_LOCAL_URL: mongodb://mongodb/messanger
      DB_REMOTE_URL: "${DB_REMOTE_URL}"
      JWT_ACCESS_TOKEN_SECRET: "${JWT_ACCESS_TOKEN_SECRET}"
      JWT_REFRESH_TOKEN_SECRET: "${JWT_REFRESH_TOKEN_SECRET}"

    
    depends_on:
      - mongodb
    
    networks:
      - mern-network


volumes:
  mongo-db: 

networks:
  mern-network: 
